---
- name: Install gitlab with web ui
  hosts: raspberry2
  become: true
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
  roles:
    - gitlab