---
- name: Install PaperMC
  hosts: minecraft_server
  become: true
  pre_tasks:
    - name: Update apt cache
      apt: 
        update_cache: yes
        cache_valid_time: 3600
  roles:
    - minecraft