---
- name: Install etcd HA and k3s HA
  hosts: k3s-cluster
  become: true
  pre_tasks:
    - name: Update apt cache
      apt: 
        update_cache: yes
        cache_valid_time: 3600
  roles:
    - etcd-multi
  