---
- name: Install Zookeeper and Kafka
  hosts: LenovoIdeapadC340
  become: true
  pre_tasks:
    - name: Update apt cache
      apt: 
        update_cache: yes
        cache_valid_time: 3600
  roles:
    - common
    - kafka-single
  