---
- name: Configure webserver with Nginx and TLS
  hosts: webservers
  become: true
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
  roles:
    - name: nginx
