- name: Run Zookeeper
  hosts: all
  become: true
  tasks:
    - name: Run Zookeeper
      shell: 
        cmd: sudo service zookeeper start
      register: zookeeper_answer

    - debug: msg="{{ zookeeper_answer }}"