- name: Run Kafka
  hosts: all
  become: true
  tasks:
    - name: Run Zookeeper
      shell: 
        cmd: bash /opt/kafka/bin/zookeeper-server-start.sh -daemon /opt/kafka/config/zookeeper.properties
      register: zookeeper_answer

    - debug: msg="{{ zookeeper_answer }}"