version: '3'
services:
  vault:
    image: vault:latest
    networks:
      vault:
    ports:
      - "{{ vault_ui_port }}":"{{ vault_ui_port }}"
    volumes:
      - vault-config:/vault/config
      - vault-policies:/vault/policies
      - vault-data:/vault/data
    environment:
      - VAULT_LOCAL_CONFIG={"ui":"{{ vault_ui_enabled }}","disable_mlock":"true","listener":{"tcp":{"address":"0.0.0.0:{{ vault_ui_port }}","tls_disable":"true"}},"backend":{"file":{"path":"/vault/file"}},"default_lease_ttl":"168h","max_lease_ttl":"0h","api_addr":"http://0.0.0.0/"}
    cap_add:
      - IPC_LOCK
    command: server
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

volumes:
  vault-config:
  vault-policies:
  vault-data:

networks:
  vault: