---
# tasks file for ./roles/local-test

- name: Open Zookeeper & SSH Ports
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
    - "{{ zookeeper_server_port }}"
    - "{{ zookeeper_server_port_alternative }}"
    - "{{ zookeeper_port }}"
    - ssh

- name: Enable UFW
  ufw:
    state: enabled
    policy: allow

- name: Copy hosts file
  copy:
    src: files/hosts
    dest: /etc/hosts


