version: '3.6'
services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    networks:
      traefik:
    ports:
      - "{{ ui_port }}:{{ ui_port }}"
    environment:
      KAFKA_BROKERCONNECT: "192.168.1.9:9092, 192.168.1.10:9092, 192.168.1.11:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    labels:
      traefik.enable: "true"
      traefik.http.routers.kafdrop.rule: 'Host("kafdrop.home.net")'
      traefik.http.services.kafdrop.loadbalancer.server.port: "9000"
      traefik.docker.network: traefik

networks:
  traefik:
    external:
      name: traefik_webgateway